export const FETCH_TODOS = "FETCH_TODOS";
export const TODOS_SUCCESS = "TODOS_SUCCESS";
export const CREATE_SUCCESS = "CREATE_SUCCESS";
export const SHOW_PRELOADER = "SHOW_PRELOADER"
export const SHOW_PRELOADER_COMPLETE = "SHOW_PRELOADER_COMPLETE";

export const USERS_SUCCESS = "USERS_SUCCESS";
export const ACCOUNT_SUCCESS = "ACCOUNT_SUCCESS";

export const ALL_REFUGEE = "ALL_REFUGEE";
export const SEARCH_PARAMS = "SEARCH_PARAMS";